server {
    listen 80;
    server_name _;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    include /etc/nginx/common-locations.conf;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/patr.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/patr.me/privkey.pem;

    include /etc/nginx/common-locations.conf;
}
